<template>
  <div class="page">
    <div class="main-title flex">
      <!-- <img src="@img/my/nav-4.png" alt="" /> -->
      <span>Customer Management</span>
    </div>

    <div class="page-ctx">
      <!-- 重要提醒部分 -->
      <div class="reminder-section">
        <div class="reminder-content">
          <span class="reminder-dot"></span>
          <span
            class="reminder-text"
          >If the customer you have bound fails to achieve any transactions within six natural months from the registration date, the customer will be automatically unbound; The unbound customer will no longer belong to you, and any sales generated by that customer after unbinding will no longer be associated with your account.</span>
        </div>
        <button @click="do_address_add()" class="btn-add-customer">
          <i class="el-icon-plus"></i>
          <span>ADD CUSTOMER</span>
        </button>
      </div>

      <!-- 客户卡片列表 -->
      <div class="customer-cards">
        <div class="customer-card" v-for="(item, index) in list_address" :key="index">
          <div class="card-content">
            <div class="card-item">
              <span class="card-label">Customer Name:</span>
              <span class="card-value">{{ item.nickname }}</span>
            </div>
            <div class="card-item">
              <span class="card-label">Business Number:</span>
              <span class="card-value">{{ item.unified_code || '123456789456123' }}</span>
            </div>
            <div class="card-item">
              <span class="card-label">Customer Email:</span>
              <span class="card-value">{{ item.email || item.unified_code || '123456789456123' }}</span>
            </div>
            <div class="card-item">
              <span class="card-label">Add Time:</span>
              <span class="card-value">{{ item.createdTime || '2025-10-10' }}</span>
            </div>
            <div class="card-item">
              <span class="card-label">Status:</span>
              <span
                class="card-value status"
                :class="{ 'status-review': item.checkStatus && item.checkStatus !== '' }"
              >{{ item.checkStatus || '' }}</span>
            </div>
          </div>
          <div class="card-delete" @click="do_address_delete(item.id)">
            <img src="@img/other/shopcart-goods-delete.png" alt="">
          </div>
        </div>

        <el-empty v-if="!list_address.length" description="No customer added"></el-empty>
      </div>
    </div>

    <!-- 添加客户信息弹窗 -->
    <el-dialog
      title="Add customer"
      :visible.sync="showModal"
      width="980px"
      :before-close="closeModal"
      :close-on-press-escape="false"
      :close-on-click-modal="false"
      custom-class="customer-modal"
    >
      <div class="modal-inner">
        <el-form :model="form" :rules="rules" ref="customerForm">
          <!-- label-width="100px" -->
          <div class="form-item">
            <span class="label required">Customer name :</span>
            <el-form-item prop="title">
              <el-input v-model="form.title" placeholder="Please enter" clearable></el-input>
            </el-form-item>
          </div>
          <div class="form-item">
            <span class="label required">Business number :</span>
            <el-form-item prop="unified_code ">
              <el-input v-model="form.unified_code " placeholder="Please enter" clearable></el-input>
            </el-form-item>
          </div>

          <div class="form-item">
            <span class="label">Customer Phone Number :</span>
            <el-form-item prop="phone">
              <el-input v-model="form.phone" placeholder="Please enter" clearable></el-input>
            </el-form-item>
          </div>

          <div class="form-item">
            <span class="label">Customer Email :</span>
            <el-form-item prop="email">
              <el-input v-model="form.email" placeholder="Please enter" clearable></el-input>
            </el-form-item>
          </div>

          <div class="form-item">
            <span class="label required">Company Address :</span>
            <el-form-item prop="companyAddress">
              <el-input v-model="form.companyAddress" placeholder="Please enter" clearable></el-input>
            </el-form-item>
          </div>

          <!-- <div class="form-item">
            <span class="label required">营业执照:</span>
            <el-form-item prop="license1">
              <div class="upload-section">
                <div class="upload-area">
                  <el-upload
                    class="upload-demo"
                    accept="image/*"
                    :name="UPLOAD_NAME"
                    :action="UPLOAD_ACTION"
                    :data="mix_upload_data"
                    :on-success="(res) => upload_on_success(res, 'license1')"
                    :before-upload="upload_before_upload"
                  >
                    <div class="upload-box" v-if="!form.license1">
                      <div class="upload-icon">+</div>
                      <div class="upload-text">上传图片</div>
                    </div>
                    <div class="uploaded-image" v-else>
                      <img :src="form.license1" alt="已上传图片" />
                      <div class="image-overlay">
                        <span class="reupload-text">重新上传</span>
                      </div>
                    </div>
                  </el-upload>
                </div>

                <div class="sample-area">
                  <div class="sample-image">
                    <img src="@img/enterprise-cert/sample1.png" alt="示意图" />
                  </div>
                  <div class="sample-text">示意图</div>
                </div>
              </div>

              <div class="upload-tips">
                <div>支持JPG/PNG格式图片</div>
                <div>不大于5M</div>
                <div>彩色扫描或复印件</div>
              </div>
            </el-form-item>
          </div>-->
        </el-form>
      </div>

      <span slot="footer" class="dialog-footer">
        <el-button class="btn-confirm" @click="throttle_do_submit()" :loading="loading">SUBMIT</el-button>
        <!-- <el-button class="btn-cancel" @click="closeModal">取消</el-button> -->
      </span>
    </el-dialog>
  </div>
</template>

<script>
import { mapState } from "vuex";
import { UPLOAD_ACTION, UPLOAD_NAME } from "@/config/env.js";

export default {
  name: "customer-management",
  components: {},
  data() {
    return {
      UPLOAD_ACTION,
      UPLOAD_NAME,
      pagination: {
        page: 1,
        pageNum: 100
      },
      list_address: [],

      // 弹窗相关
      showModal: false,
      loading: false,

      // 表单数据
      form: {
        title: "",
        phone: "",
        email: "",
        license1: "",
        unified_code: ""
      },

      // 表单验证规则
      rules: {
        title: [{ required: true, message: "Please enter the company name", trigger: "blur" }],
        unified_code: [
          { required: true, message: "Please enter the unified social credit code", trigger: "blur" }
        ],
        // phone: [
        //   { required: true, message: "请输入手机号", trigger: "blur" },
        //   {
        //     pattern: /^1[3-9]\d{9}$/,
        //     message: "请输入正确的手机号",
        //     trigger: "blur",
        //   },
        // ],
        // email: [
        //   { required: true, message: "请输入邮箱", trigger: "blur" },
        //   { type: "email", message: "请输入正确的邮箱格式", trigger: "blur" },
        // ],
        license1: [
          { required: true, message: "Please upload the business license", trigger: "change" }
        ]
      }
    };
  },
  computed: {
    ...mapState([""])
  },
  created() {
    this.setView();
    this.throttle_do_submit = this.mix_throttle(this.do_submit, 1000);
  },
  methods: {
    throttle_do_submit() {},

    setView() {
      this.$api({
        url: "/service.php",
        method: "get",
        data: {
          action: "users_getCustomerList",
          ...this.pagination
        }
      }).then(res => {
        if (res.code == 200) {
          let data = res.data;
          this.list_address = data.list;
        }
      });
    },

    // 打开添加客户弹窗
    do_address_add() {
      this.showModal = true;
      this.resetForm();
    },

    // 删除客户
    do_address_delete(id) {
      this.$confirm("Are you sure you want to delete this customer?", "Tips", {
        confirmButtonText: "Yes",
        cancelButtonText: "No",
        type: "warning"
      })
        .then(() => {
          this.$api({
            url: "/service.php",
            method: "post",
            data: {
              action: "users_deleteCustomer",
              id: id
            }
          }).then(res => {
            if (res.code == 200) {
              this.$message.success("Delete successfully");
              this.setView();
            } else {
              this.$message.error(res.msg || "Delete failed");
            }
          });
        })
        .catch(() => {});
    },

    // 重置表单
    resetForm() {
      this.form = {
        nickname: "",
        phone: "",
        email: "",
        license1: ""
      };
      this.$nextTick(() => {
        this.$refs.customerForm && this.$refs.customerForm.clearValidate();
      });
    },

    // 关闭弹窗
    closeModal() {
      this.showModal = false;
      this.resetForm();
    },

    // 提交表单
    do_submit() {
      this.$refs.customerForm.validate(valid => {
        if (valid) {
          this.loading = true;

          this.$api({
            url: "/service.php",
            method: "post",
            data: {
              action: "users_saveUserCompany",
              ...this.form
            }
          }).then(res => {
            let { code, msg } = res;
            alert(res).then(() => {
              this.loading = false;
            });
            if (code == 200) {
              this.closeModal();
              this.setView();
            }
          });
        } else {
          return false;
        }
      });
    },

    // 上传相关
    upload_on_success(res, field) {
      let { code, data, msg } = res;
      alert(res);
      if (code == 200) {
        this.form[field] = res.data;
        // 触发表单验证
        this.$nextTick(() => {
          this.$refs.customerForm.validateField(field);
        });
      }
    },

    upload_before_upload(file) {
      const isLt5M = file.size / 1024 / 1024 < 5; // 文件大小限制5M
      if (!isLt5M) {
        alertErr("The file size cannot exceed 5MB!");
        return false;
      }

      const isJPG = file.type === "image/jpeg" || file.type === "image/png";
      if (!isJPG) {
        alertErr("The file can only be JPG/PNG format!");
        return false;
      }

      return true;
    }
  }
};
</script>

<style scoped lang="less">
.page {
  text-align: left;
  padding-bottom: 80px;

  .main-title {
    padding: 0 32px;
    text-align: left;
    height: 70px;
    line-height: 70px;
    background: #ffffff;
    font-size: 20px;
    font-family: Microsoft YaHei-Bold, Microsoft YaHei;
    font-weight: bold;
    color: #1e262e;
    img {
      width: 22px;
      margin-right: 10px;
    }
  }

  .page-ctx {
    margin-top: 24px;
    padding: 32px;
    background: #fff;

    // 重要提醒部分
    .reminder-section {
      display: flex;
      justify-content: space-between;
      margin-bottom: 24px;
      padding-bottom: 24px;
      gap: 108px;

      .reminder-content {
        display: flex;
        align-items: flex-start;
        flex: 1;
        margin-right: 24px;

        .reminder-dot {
          display: inline-block;
          width: 6px;
          height: 6px;
          background: #ff0000;
          border-radius: 50%;
          margin-right: 8px;
          margin-top: 6px;
          flex-shrink: 0;
        }

        .reminder-text {
          font-size: 20px;
          color: #1f1f1f;
          line-height: 30px;
        }
      }

      .btn-add-customer {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
        width: 300px;
        height: 80px;
        background: #ec6a2b;
        border-radius: 10px 10px 10px 10px;
        font-size: 20px;
        color: #ffffff;
        font-weight: 400;
        cursor: pointer;

      }
    }

    // 客户卡片列表
    .customer-cards {
      display: flex;
      flex-direction: column;
      gap: 30px;

      .customer-card {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background: #fff;
        border: 1px solid #e5e5e5;
        border-radius: 4px;
        padding: 30px 40px;
        transition: box-shadow 0.3s;

        &:hover {
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }

        .card-delete {
          width: 44px;
          height: 44px;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          img {
            width: 100%;
            height: 100%;
          }
        }

        .card-content {
          display: flex;
          flex-direction: column;
          gap: 12px;
          padding-right: 40px;

          .card-item {
            display: flex;
            align-items: flex-start;

            .card-label {
              font-size: 20px;
              color: #5E5E5E;
              min-width: 180px;
              margin-right: 12px;
              text-align: right;
            }

            .card-value {
              font-size: 20px;
              color: #1f1f1f;
              flex: 1;
              word-break: break-all;

              &.status {
                &.status-review {
                  color: #ec6a2b;
                }
              }
            }
          }
        }
      }
    }
  }
}
</style>

<style scoped lang="less" src="@/assets/h5css/user/address-list.less"></style>
<style scoped lang="less" src="@/assets/h5css/page/shipei3.less"></style>

<!-- 弹窗样式 -->
<style scoped lang="less">
/deep/ .customer-modal {
  min-width: 40vw;

  .modal-inner {
    padding: 0 68px;
    .form-item {
      margin-bottom: 20px;
      display: flex;
      align-items: flex-start;

      .label {
        width: 263px;
        text-align: right;
        font-size: 20px;
        color: #1e262e;
        margin-right: 10px;
        line-height: 56px;

        &.required {
          &::before {
            margin-right: 3px;
            content: "*";
            color: #ff0000;
          }
        }
      }

      .el-form-item {
        flex: 1;
        margin-bottom: 0;

        .el-input {
          width: 100%;

          .el-input__inner {
            border: 1px solid #dbdbdb;
            border-radius: 6px;
            font-size: 20px;
            color: #606266;
            height: 56px;
            line-height: 56px;

            &:focus {
              border-color: #00306B;
            }
          }
        }
      }

      .upload-section {
        display: flex;
        gap: 20px;
        margin-bottom: 15px;

        .upload-area {
          .upload-box {
            width: 120px;
            height: 120px;
            border: 2px dashed #be9bdf;
            border-radius: 8px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            transition: all 0.3s ease;
            background: #fff;

            &:hover {
              border-color: #00306B;
              background: #f7efff;
            }

            .upload-icon {
              font-size: 30px;
              color: #be9bdf;
              margin-bottom: 8px;
            }

            .upload-text {
              font-size: 12px;
              color: #be9bdf;
              text-align: center;
            }
          }

          .uploaded-image {
            position: relative;
            width: 120px;
            height: 120px;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            overflow: hidden;
            cursor: pointer;

            img {
              width: 100%;
              height: 100%;
              object-fit: cover;
            }

            .image-overlay {
              position: absolute;
              top: 0;
              left: 0;
              right: 0;
              bottom: 0;
              background: rgba(0, 0, 0, 0.5);
              display: flex;
              align-items: center;
              justify-content: center;
              opacity: 0;
              transition: opacity 0.3s ease;

              .reupload-text {
                color: #ffffff;
                font-size: 12px;
                font-weight: 500;
              }
            }

            &:hover .image-overlay {
              opacity: 1;
            }
          }
        }

        .sample-area {
          .sample-image {
            width: 120px;
            height: 120px;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            overflow: hidden;
            background: #f5f5f5;
            display: flex;
            align-items: center;
            justify-content: center;

            img {
              width: 100%;
              height: 100%;
              object-fit: cover;
            }
          }

          .sample-text {
            text-align: center;
            font-size: 12px;
            color: #1f1f1f;
            margin-top: 8px;
          }
        }
      }

      .upload-tips {
        font-size: 12px;
        color: #505050;
        line-height: 1.5;

        div {
          margin-bottom: 2px;
        }
      }
    }
  }
}

/deep/ .el-dialog__header {
  padding: 16px 24px;
  background: #fff;
  font-family: Microsoft YaHei, Microsoft YaHei;
  font-weight: 600;
  font-size: 24px;
  color: #1e262e;

  .el-dialog__close {
    font-size: 20px;
  }
}

/deep/ .el-dialog__body {
  padding: 36px 60px 36px 0;
}

/deep/ .el-dialog__footer {
  text-align: center;
  padding-bottom: 50px;

  .btn-confirm {
    width: 192px;
    height: 52px;
    background: #ec6a2b;
    border-radius: 6px 6px 6px 6px;
    font-family: Microsoft YaHei, Microsoft YaHei;
    font-weight: 400;
    font-size: 20px;
    color: #ffffff;
  }

  .btn-cancel {
    width: 104px;
    height: 40px;
    background: #ffffff;
    border-radius: 50px;
    border: 1px solid #d4d4d4;
    font-family: Microsoft YaHei, Microsoft YaHei;
    font-weight: 400;
    font-size: 14px;
    color: #1f1f1f;

    &:hover {
      border-color: #00306B;
      color: #00306B;
    }
  }
}
</style>
